version: '3.1'

# this is a build example. builds a custom image as a proxy server, launches a website that points to an existing mount pount where html files exist
# proxy server needs port 80

services: # containers. same as docker run.

  drupalrp:
    image: drupal:latest
    ports: 
      - '80:80'
  
  postgresrp:
    image: postgres
    ports:
      - 443
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passw0rdda
    volumes: 
        - './datadrupalmodules:/var/www/html/modules'

  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports: 
      - '80:80'
  
 web:
    image: httpd
    volumes: 
        - './html:/usr/local/apache2/htdocs/'
