version: '3.1'

services: # containers. same as docker run.
  drupalrp:
    image: drupal:latest
    ports: 
      - '8080:80'
  
  postgresrp:
    image: postgres
    ports:
      - 443
    environment:
      POSTGRES_DB:drupal
      POSTGRES_USER:user
      POSTGRES_PASSWORD:passw0rdda
    volumes: 
      - drupal-modules:/var/www/html/modules
  
  
 ## Example:
 # same as docker run -p 80:4000 -v $(pwd):/site bretfisher/jekyll-serve
 #
 # services:
 #    jekyll:
 #       image: bretfisher/jekyll-serve
 #       volume:
 #         - .:/site  (note: compose understands that . is the same as $(pwd)
 #       ports:
 #         - '80:4000'
